blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_list, name="blog_list"),
    path("blog_detail/<slug>/", views.blog_detail, name="blog_detail"),
    path("create_comment/<slug>/", views.create_comment, name="create_comment"),
    path("like_blog/", views.like_blog, name="like_blog"),
]

customer/urls.py
from django.urls import path
from customer import views

app_name = "customer"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("orders/", views.orders, name="orders"),
    path("order_detail/<str:order_id>/", views.order_detail, name="order_detail"),
    path("order_item_detail/<str:order_id>/<item_id>/", views.order_item_detail, name="order_item_detail"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("remove_from_wishlist/<id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("add_to_wishlist/<id>/", views.add_to_wishlist, name="add_to_wishlist"),
    path("addresses/", views.addresses, name="addresses"),
    path("notis/", views.notis, name="notis"),
    path("mark_noti_seen/<id>/", views.mark_noti_seen, name="mark_noti_seen"),
    path("address_detail/<id>/", views.address_detail, name="address_detail"),
    path("address_create/", views.address_create, name="address_create"),
    path("delete_address/<id>/", views.delete_address, name="delete_address"),
    path("profile/", views.profile, name="profile"),
    path("change_password/", views.change_password, name="change_password"),
]

ecom_proj/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('userauths.urls')),
    path('customer/', include('customer.urls')),
    path('vendor/', include('vendor.urls')),
    path('manager/', include('manager.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

# Serve static files (already handled by WhiteNoise in production)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# ✅ Serve media files in both debug and production
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", views.shop, name="shop"),
    path("category/<slug:slug>/", views.category_detail, name="category_detail"),
    path("category/<id>/", views.category, name="category"),
    path("categories/", views.category_list, name="category_list"),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('delete_cart_item/', views.delete_cart_item, name='delete_cart_item'),
    path('create_order/', views.create_order, name='create_order'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('remove_from_wishlist/<int:id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('search/', views.search, name='search'),

    # Checkout & shipping
    path('checkout/<str:order_id>/', views.checkout, name='checkout'),
    path('checkout/<str:order_id>/update-shipping/', views.update_shipping, name='update_shipping'),  # <— NEW

    path('coupon_apply/<str:order_id>/', views.coupon_apply, name='coupon_apply'),

    path("filter_products/", views.filter_products, name="filter_products"),

    # Payment URLs
    path('cod_payment/<str:order_id>/', views.cod_payment, name='cod_payment'),
    path('credit_card_payment/<str:order_id>/', views.credit_card_payment, name='credit_card_payment'),
    path('jazzcash_payment/<str:order_id>/', views.jazzcash_payment, name='jazzcash_payment'),
    path('easypaisa_payment/<str:order_id>/', views.easypaisa_payment, name='easypaisa_payment'),
    path('payment_status/<str:order_id>/', views.payment_status, name='payment_status'),

    path("order_tracker_page/", views.order_tracker_page, name="order_tracker_page"),
    path("order_tracker_detail/<str:order_id>/", views.order_tracker_detail, name="order_tracker_detail"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_conditions/", views.terms_conditions, name="terms_conditions"),
]

userauths/urls.py
from django.urls import path, reverse_lazy
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path("sign-up/", views.register, name="sign-up"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    
    path("password-reset/", views.reset_password_request, name="password_reset"),
    path("password-reset/security/", views.reset_password_security, name="reset_password_security"),
    path("password-reset/new/", views.set_new_password, name="set_new_password"),
]

customer/models.py
from django.db import models

from store.models import Product
from userauths.models import User

# Create your models here.
TYPE = (
    ('New Order', 'New Order'),
    ('Item Shipped', 'Item Shipped'),
    ('Item Delivered', 'Item Delivered'),
)

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='Wishlist')
    wishlist_id = models.CharField(max_length=100, blank=True, null=True)  # for guests

    class Meta:
        verbose_name_plural = 'Wishlist'

    def __str__(self):
        if self.product.name:
            return self.product.name
        else:
            return "Wishlist"
    
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    full_name = models.CharField(max_length=200, null=True, blank=True, default=None)
    mobile = models.CharField(max_length=50, null=True, blank=True, default=None)
    email = models.CharField(max_length=100, null=True, blank=True, default=None)
    country = models.CharField(max_length=100, null=True, blank=True, default=None)
    state = models.CharField(max_length=100, null=True, blank=True, default=None)
    city = models.CharField(max_length=100, null=True, blank=True, default=None)
    address = models.CharField(max_length=100, null=True, blank=True, default=None)
    zip_code = models.CharField(max_length=100, null=True, blank=True, default=None)

    class Meta:
        verbose_name_plural = 'Customer Address'

    def __str__(self):
        return self.full_name

class Notifications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    type = models.CharField(max_length=100, choices=TYPE , default=None)
    seen = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Notifications"

    def __str__(self):
        return self.type

customer/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.db import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth import update_session_auth_hash

from plugin.paginate_queryset import paginate_queryset
from store import models as store_models
from customer import models as customer_models

@login_required
def dashboard(request):
    orders = store_models.Order.objects.filter(customer=request.user)
    total_spent = store_models.Order.objects.filter(customer=request.user).aggregate(total = models.Sum("total"))['total']
    notis = customer_models.Notifications.objects.filter(user=request.user, seen=False)

    context = {
        "orders": orders,
        "total_spent": total_spent,
        "notis": notis,
    }

    return render(request, "customer/dashboard.html", context)

@login_required
def orders(request):
    orders = store_models.Order.objects.filter(customer=request.user)

    context = {
        "orders": orders,
    }

    return render(request, "customer/orders.html", context)

@login_required
def order_detail(request, order_id):
    from django.shortcuts import get_object_or_404
    order = get_object_or_404(store_models.Order, customer=request.user, order_id=order_id)
    
    context = {"order": order}
    return render(request, "customer/order_detail.html", context)

@login_required
def order_item_detail(request, order_id, item_id):
    order = store_models.Order.objects.get(customer=request.user, order_id=order_id)
    item = store_models.OrderItem.objects.get(order=order, item_id=item_id)
    
    context = {
        "order": order,
        "item": item,
    }

    return render(request, "customer/order_item_detail.html", context)



@login_required
def wishlist(request):
    wishlist_list = customer_models.Wishlist.objects.filter(user=request.user)
    wishlist = paginate_queryset(request, wishlist_list, 6)

    context = {
        "wishlist": wishlist,
        "wishlist_list": wishlist_list,
    }
    
    return render(request, "customer/wishlist.html", context)

@login_required
def remove_from_wishlist(request, id):
    wishlist = customer_models.Wishlist.objects.get(user=request.user, id=id)
    wishlist.delete()
    
    messages.success(request, "item removed from wishlist")
    return redirect("customer:wishlist")


def add_to_wishlist(request, id):
    if request.user.is_authenticated:
        product = store_models.Product.objects.get(id=id)
        customer_models.Wishlist.objects.create(product=product, user=request.user)
        wishlist = customer_models.Wishlist.objects.filter(user=request.user)
        return JsonResponse({"message": "Item added to wishlist", "wishlist_count": wishlist.count()})
    else:
        return JsonResponse({"message": "User is not logged in", "wishlist_count": "0"})




@login_required
def notis(request):
    notis_list = customer_models.Notifications.objects.filter(user=request.user, seen=False)
    notis = paginate_queryset(request, notis_list, 10)

    context = {
        "notis": notis,
        "notis_list": notis_list,
    }
    return render(request, "customer/notis.html", context)

@login_required
def mark_noti_seen(request, id):
    noti = customer_models.Notifications.objects.get(user=request.user, id=id)
    noti.seen = True
    noti.save()

    messages.success(request, "Notification marked as seen")
    return redirect("customer:notis")


@login_required
def addresses(request):
    addresses = customer_models.Address.objects.filter(user=request.user)
    context = {
        "addresses": addresses,
    }

    return render(request, "customer/addresses.html", context)

@login_required
def address_detail(request, id):
    address = customer_models.Address.objects.get(user=request.user, id=id)
    
    if request.method == "POST":
        full_name = request.POST.get("full_name")
        mobile = request.POST.get("mobile")
        email = request.POST.get("email")
        country = request.POST.get("country")
        state = request.POST.get("state")
        city = request.POST.get("city")
        address_location = request.POST.get("address")
        zip_code = request.POST.get("zip_code")

        address.full_name = full_name
        address.mobile = mobile
        address.email = email
        address.country = country
        address.state = state
        address.city = city
        address.address = address_location
        address.zip_code = zip_code
        address.save()

        messages.success(request, "Address updated")
        return redirect("customer:address_detail", address.id)
    
    context = {
        "address": address,
    }

    return render(request, "customer/address_detail.html", context)

@login_required
def address_create(request):
    # Get the next URL from query params (default to addresses page)
    next_url = request.GET.get('next', None) or "customer:addresses"

    if request.method == "POST":
        full_name = request.POST.get("full_name")
        mobile = request.POST.get("mobile")
        email = request.POST.get("email")
        country = request.POST.get("country")
        state = request.POST.get("state")
        city = request.POST.get("city")
        address = request.POST.get("address")
        zip_code = request.POST.get("zip_code")

        customer_models.Address.objects.create(
            user=request.user,
            full_name=full_name,
            mobile=mobile,
            email=email,
            country=country,
            state=state,
            city=city,
            address=address,
            zip_code=zip_code,
        )

        messages.success(request, "Address created")
        return redirect(next_url)  # redirect dynamically

    return render(request, "customer/address_create.html", {"next": next_url})

def delete_address(request, id):
    address = customer_models.Address.objects.get(user=request.user, id=id)
    address.delete()
    messages.success(request, "Address deleted")
    return redirect("customer:addresses")

@login_required
def profile(request):
    profile = request.user.profile

    if request.method == "POST":
        image = request.FILES.get("image")
        full_name = request.POST.get("full_name")
        mobile = request.POST.get("mobile")
    
        if image != None:
            profile.image = image

        profile.full_name = full_name
        profile.mobile = mobile

        request.user.save()
        profile.save()

        messages.success(request, "Profile Updated Successfully")
        return redirect("customer:profile")
    
    context = {
        'profile':profile,
    }
    return render(request, "customer/profile.html", context)

@login_required
def change_password(request):
    if request.method == "POST":
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        confirm_new_password = request.POST.get("confirm_new_password")

        if confirm_new_password != new_password:
            messages.error(request, "Confirm Password and New Password Does Not Match")
            return redirect("customer:change_password")
        
        if check_password(old_password, request.user.password):
            request.user.set_password(new_password)
            request.user.save()
            update_session_auth_hash(request, request.user)
            messages.success(request, "Password Changed Successfully")
            return redirect("customer:profile")
        else:
            messages.error(request, "Old password is not correct")
            return redirect("customer:change_password")
    
    return render(request, "customer/change_password.html")

templates/customer/dashboard.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}
<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'store:index' %}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'customer:dashboard' %}">Customer</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="middle">
    <div class="container">
        <div class="row align-items-start justify-content-between">
             {% include 'customer/sidebar.html' %}

            <div class="col-12 col-md-12 col-lg-8 col-xl-8">
                <div class="row mb-4">
                    <h4 class="mb-0 mb-4 fw-bold">Dashboard</h4>

                    <div class="col-sm-6 col-lg-4 mb-3 mb-lg-0">
                        <div class="d-flex justify-content-center align-items-center p-4 shadow-sm rounded">
                            <span class="display-6 text-danger">
                                <i class="fas fa-shopping-cart text-danger"></i>
                            </span>
                            <div class="ms-4">
                                <div class="d-flex">
                                    <h5 class="mb-0 fw-bold">{{orders.count}}</h5>
                                </div>
                                <p class="mb-0 h6 fw-semibold">Orders</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-4 mb-3 mb-lg-0">
                        <div class="d-flex justify-content-center align-items-center p-4 shadow-sm rounded">
                            <span class="display-6 text-danger">
                                <i class="fas fa-wallet text-warning"></i>
                            </span>
                            <div class="ms-4">
                                <div class="d-flex">
                                    <h5 class="mb-0 fw-bold">${{total_spent|floatformat:2|intcomma|default:"0.00"}}</h5>
                                </div>
                                <p class="mb-0 h6 fw-semibold">Total Spent</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-4 mb-3 mb-lg-0">
                        <div class="d-flex justify-content-center align-items-center p-4 shadow-sm rounded">
                            <span class="display-6 text-danger">
                                <i class="fas fa-bell text-primary"></i>
                            </span>
                            <div class="ms-4">
                                <div class="d-flex">
                                    <h5 class="mb-0 fw-bold">{{notis.count}}</h5>
                                </div>
                                <p class="mb-0 h6 fw-semibold">Notifications</p>
                            </div>
                        </div>
                    </div>
                </div>

                
                {% for order in orders %}
                    <div class="ord_list_wrap border mb-4 mfliud">
                        <div class="ord_list_head bg-light bg-opacity-10 d-flex align-items-center justify-content-between px-3 py-3">
                            <div class="olh_flex">
                                <p class="m-0 p-0"><span class="text-muted">Order Number</span></p>
                                <h6 class="mb-0 ft-medium">#{{order.order_id}}</h6>
                            </div>
                            <div class="olh_flex">
                                <a href="{% url 'customer:order_detail' order.order_id %}" class="btn btn-sm bg-primary rounded text-white">View Order <i class="fas fa-arrow-right ms-2"></i></a>
                                
                                {% if order.payment_status == "Failed" %}
                                    <a href="{% url 'store:checkout' order.order_id %}" class="btn btn-sm bg-danger rounded text-white">Retry Payment <i class="fas fa-rotate ms-2"></i></a>
                                {% endif %}
                                    
                            </div>
                        </div>
                        <div class="ord_list_body text-left">
                            <!-- Single Item -->
                            
                            {% for item in order.order_items.all %}
                                <div class="row align-items-center justify-content-center m-0 py-4 br-bottom">
                                    <div class="col-xl-6 col-lg-5 col-md-5 col-12">
                                        <div class="cart_single d-flex align-items-start mfliud-bot gap-3">
                                            <div class="cart_selected_single_thumb">
                                                <a href="{% url 'store:product_detail' item.product.slug %}"><img src="{{item.product.image.url}}" width="75" class="img-fluid rounded" alt="" /></a>
                                            </div>
                                            <div class="cart_single_caption pl-3">
                                                <h4 class="product_title fs-sm ft-medium mb-1 lh-1"> <a href="{% url 'store:product_detail' item.product.slug %}">{{item.product.name}}</a></h4>
                                                <p class="mb-2">
                                                    <span class="text-dark medium">Vendor: {{item.product.vendor.profile.full_name}}</span> <br />
                                                    
                                                    {% if item.color %}
                                                        <span class="text-dark medium">Color: {{item.color}}</span>
                                                    {% endif %}

                                                    {% if item.size %}
                                                        <span class="text-dark medium">Size: {{item.size}}</span>
                                                    {% endif %}
                                                        
                                                </p>
                                                <h4 class="fs-sm ft-bold mb-0 lh-1">${{item.price}}</h4>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xl-2 col-lg-3 col-md-3 col-6">
                                        <p class="mb-1 p-0"><span class="text-muted">Status</span></p>
                                        <div class="delv_status"><span class="ft-medium small text-warning bg-light-warning rounded px-3 py-1">{{order.order_status}}</span></div>
                                    </div>
                                    <div class="col-xl-2 col-lg-4 col-md-4 col-6">
                                        <p class="mb-1 p-0"><span class="text-muted">Payment Status</span></p>
                                        <h6 class="mb-0 ft-medium fs-sm">{{order.payment_status}}</h6>
                                    </div>
                                    <div class="col-xl-2 col-lg-4 col-md-4 col-6">
                                        <p class="mb-1 p-0"><span class="text-muted">Order Date/Time</span></p>
                                        <h6 class="mb-0 ft-medium fs-sm">{{order.date}}</h6>
                                    </div>
                                </div>
                            {% endfor %}
                                
                        </div>
                        <div class="ord_list_footer d-flex align-items-center justify-content-between br-top px-3">
                            <div class="col-xl-12 pr-0 py-2 olf_flex d-flex align-items-center justify-content-between">
                                <div class="olf_flex_inner hide_mob">
                                    <p class="m-0 p-0"><span class="text-muted medium">Paid using {{order.payment_method}}</span></p>
                                </div>
                                <div class="float-end"><h5 class="mb-0 fs-sm ft-bold">Total: ${{order.total|floatformat:2|intcomma}}</h5></div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                <p>No orders yet</p>
                {% endfor %}
                    
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/customer/orders.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}
<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Customer</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Orders</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="middle">
    <div class="container">
        <div class="row align-items-start justify-content-between">
             {% include 'customer/sidebar.html' %}

            <div class="col-12 col-md-12 col-lg-8 col-xl-8">
                <div class="row mb-4">
                    <h4 class="mb-0 mb-4 fw-bold">Orders</h4>
                </div>

                
                {% for order in orders %}
                    <div class="ord_list_wrap border mb-4 mfliud">
                        <div class="ord_list_head bg-light bg-opacity-10 d-flex align-items-center justify-content-between px-3 py-3">
                            <div class="olh_flex">
                                <p class="m-0 p-0"><span class="text-muted">Order Number</span></p>
                                <h6 class="mb-0 ft-medium">#{{order.order_id}}</h6>
                            </div>
                            <div class="olh_flex">
                                <a href="{% url 'customer:order_detail' order.order_id %}" class="btn btn-sm bg-primary rounded text-white">View Order <i class="fas fa-arrow-right ms-2"></i></a>
                                
                                {% if order.payment_status == "Failed" %}
                                    <a href="{% url 'store:checkout' order.order_id %}" class="btn btn-sm bg-danger rounded text-white">Retry Payment <i class="fas fa-rotate ms-2"></i></a>
                                {% endif %}
                                    
                            </div>
                        </div>
                        <div class="ord_list_body text-left">
                            <!-- Single Item -->
                            
                            {% for item in order.order_items.all %}
                                <div class="row align-items-center justify-content-center m-0 py-4 br-bottom">
                                    <div class="col-xl-6 col-lg-5 col-md-5 col-12">
                                        <div class="cart_single d-flex align-items-start mfliud-bot gap-3">
                                            <div class="cart_selected_single_thumb">
                                                <a href="{% url 'store:product_detail' item.product.slug %}"><img src="{{item.product.image.url}}" width="75" class="img-fluid rounded" alt="" /></a>
                                            </div>
                                            <div class="cart_single_caption pl-3">
                                                <h4 class="product_title fs-sm ft-medium mb-1 lh-1"> <a href="{% url 'store:product_detail' item.product.slug %}">{{item.product.name}}</a></h4>
                                                <p class="mb-2">
                                                    <span class="text-dark medium">Vendor: {{item.product.vendor.profile.full_name}}</span> <br />
                                                    
                                                    {% if item.color %}
                                                        <span class="text-dark medium">Color: {{item.color}}</span>
                                                    {% endif %}

                                                    {% if item.size %}
                                                        <span class="text-dark medium">Size: {{item.size}}</span>
                                                    {% endif %}
                                                        
                                                </p>
                                                <h4 class="fs-sm ft-bold mb-0 lh-1">${{item.price}}</h4>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xl-2 col-lg-3 col-md-3 col-6">
                                        <p class="mb-1 p-0"><span class="text-muted">Status</span></p>
                                        <div class="delv_status"><span class="ft-medium small text-warning bg-light-warning rounded px-3 py-1">{{order.order_status}}</span></div>
                                    </div>
                                    <div class="col-xl-2 col-lg-4 col-md-4 col-6">
                                        <p class="mb-1 p-0"><span class="text-muted">Payment Status</span></p>
                                        <h6 class="mb-0 ft-medium fs-sm">{{order.payment_status}}</h6>
                                    </div>
                                    <div class="col-xl-2 col-lg-4 col-md-4 col-6">
                                        <p class="mb-1 p-0"><span class="text-muted">Order Date/Time</span></p>
                                        <h6 class="mb-0 ft-medium fs-sm">{{order.date}}</h6>
                                    </div>
                                </div>
                            {% endfor %}
                                
                        </div>
                        <div class="ord_list_footer d-flex align-items-center justify-content-between br-top px-3">
                            <div class="col-xl-12 pr-0 py-2 olf_flex d-flex align-items-center justify-content-between">
                                <div class="olf_flex_inner hide_mob">
                                    <p class="m-0 p-0"><span class="text-muted medium">Paid using {{order.payment_method}}</span></p>
                                </div>
                                <div class="float-end"><h5 class="mb-0 fs-sm ft-bold">Total: ${{order.total|floatformat:2|intcomma}}</h5></div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                <p>No orders yet</p>
                {% endfor %}
                    
            </div>
        </div>
    </div>
</section>
{% endblock content %}